### ISSUE TITLE
Nov 17th: First Meeting Notes

### ISSUE THREAD

**Issue by tzoght** [UBC-MDS/heart_disease_predictor#1]
## Reading Material for the project
1. https://pages.github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students/materials/assignments/milestone1.html#3-a-script-that-downloads-and-saves-the-data 
2. Reference repo: https://github.com/ttimbers/breast_cancer_predictor/tree/v1.1

**Comment by tzoght** [comment]
[x] Team work contract 
[ ] Proof read the contract
[ ] Code of Conduct file - Tony
[ ] Contributing file - Tony
[ ] License file  - Tony
[ ] Download scripts - Tony
[ ] Proof reading the proposal - 
[ ] EDA 
[ ] Re-read Expectations

**Comment by elenagan** [comment]
Completed
