### ISSUE TITLE
Scaffolding of report

### ISSUE THREAD

**Issue by elenagan** [UBC-MDS/heart_disease_predictor#12]
Make the different sections of the jupyter notebook with titles etc.

**Comment by tzoght** [comment]
Task completed, the structure was reviewed and adopted by the team, we decided to go with the following:

*  data
      *  raw
            * (raw dataset)
      * processed
            * (processed and tidy dataset)
* doc
       * heart_disease_prediction_report
       * (any misc jupyter notebooks for EDA)
*  results
       * (findings and plots generated by scripts)
 * src
       * (python scripts for download, pre-process, eda and model)

**Comment by tzoght** [comment]
Closing
